package org.atemsource.atem.service.identity;

public class Identity {
	
	public static final String META_ATTRIBUTE_CODE = "identity";
	private String attributeCode;
	private boolean autoGenerated;

	public String getAttributeCode() {
		return attributeCode;
	}

	public void setAttributeCode(String attributeCode) {
		this.attributeCode = attributeCode;
	}

	public boolean isAutoGenerated() {
		return autoGenerated;
	}

	public void setAutoGenerated(boolean autoGenerated) {
		this.autoGenerated = autoGenerated;
	}
}
